name: Deploy to Staging

on:
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"]
    branches: [dev]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}

      - name: Deploy backend
        run: |
          rsync -avz -e ssh backend/ ${{ secrets.STAGING_SERVER }}:/opt/taki/backend
          ssh ${{ secrets.STAGING_SERVER }} "cd /opt/taki/backend && npm install --production && pm2 restart taki-backend"

      - name: Deploy frontend
        run: |
          rsync -avz -e ssh frontend/dist/ ${{ secrets.STAGING_SERVER }}:/var/www/taki-frontend